"""Normalize free-text LLM path names to canonical career path labels.

Reads canonical paths and path aliases from search-config.json
(generated by onboarding). Falls back to pass-through if no config exists yet.
"""
from __future__ import annotations

import json
from pathlib import Path

CONFIG_PATH = Path(__file__).resolve().parents[2] / "data" / "search-config.json"

# Lazy-loaded cache
_cache: dict | None = None


def _load() -> dict:
    """Load and cache config. Returns empty structure if file missing."""
    global _cache
    if _cache is not None:
        return _cache

    _cache = {"paths": {}, "path_aliases": {}, "company_aliases": {}}

    if not CONFIG_PATH.exists():
        return _cache

    try:
        config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return _cache

    # Build case-insensitive path lookup from query_pack labels
    for pack in config.get("query_packs", {}).values():
        label = pack.get("label", "")
        if label:
            _cache["paths"][label.strip().lower()] = label

    # Path aliases: fuzzy LLM variants -> canonical labels
    for variant, canonical in config.get("path_aliases", {}).items():
        _cache["path_aliases"][variant.strip().lower()] = canonical

    # Company name aliases
    for variant, canonical in config.get("company_aliases", {}).items():
        _cache["company_aliases"][variant.strip().lower()] = canonical

    return _cache


def normalize_path(raw_name: str, canonical_paths: list[str] | None = None) -> str:
    """Map raw LLM path name to canonical label via case-insensitive lookup.

    Args:
        raw_name: The path name to normalize.
        canonical_paths: Ignored (kept for backwards compatibility).

    Returns:
        Canonical label if a match is found, otherwise raw_name unchanged.
    """
    if not raw_name:
        return raw_name
    cache = _load()
    key = raw_name.strip().lower()
    # Try exact match on query_pack labels first, then fuzzy aliases
    return cache["paths"].get(key) or cache["path_aliases"].get(key) or raw_name


def normalize_company(name: str) -> str:
    """Normalize company name to canonical form via alias lookup."""
    if not name:
        return name
    cache = _load()
    return cache["company_aliases"].get(name.strip().lower(), name)


def get_canonical_paths() -> list[str]:
    """Return the list of canonical path labels from search-config.json."""
    cache = _load()
    return list(cache["paths"].values())
